name: Bundle and deploy to AliYun

on:
  # push:
  #   branches:
  #     - main
  release:
    types: [published]

jobs:
  bundle-and-deploy:
    runs-on: windows-latest
    
    env:
      IIS_SERVER_COMPUTER_NAME: ${{ secrets.IIS_SERVER_COMPUTER_NAME }}
      IIS_SERVER_USERNAME: ${{ secrets.IIS_SERVER_USERNAME }}
      IIS_SERVER_PASSWORD: ${{ secrets.IIS_SERVER_PASSWORD }}
      IIS_WEBSITE_NAME: slaveOftime-site
      RECYCLE_APP_NAME: slaveOftime-site
      WEBSITE_CONTENT_PATH: "C:\\www\\slaveOftime-site"
      RELEASE_VERSION: ${{ github.event.release.tag_name }}

    steps:
    - uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 6.0.x

    - name: Deploy
      run: dotnet fsi .\build.fsx -t Deploy
